### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [Dica-Developer/weplantaforest#103]
Hello @Gab0rB 

I designed a logo for weplantaforest. I made a logo by staying true to the idea of the project. What do you think the logo? I will wait for feedback.

If you like it, i can send a pr.

![wp](https://user-images.githubusercontent.com/36298335/44093625-bae8736e-9fdc-11e8-9c17-616713ee8184.jpg)

**Comment by mschaaf** [comment]
@reallinfo Sorry for the very late answer. We like your logo and would like to use it on our Github frontpage page. If you still want to contribute we would like to split the above image into two separate.
