### ISSUE TITLE
What can we do to prevent FetchType.EAGER for Tree#_type

### ISSUE THREAD

**Issue by sebfroh** [Dica-Developer/weplantaforest#11]
I changed the FetchType.EAGER from FetchType.LAZY to get the id of the TreeType of a specific Tree to generate the correct JSON-HAL link.
I'm sure we find a way which is more performant to do this.

**Comment by mschaaf** [comment]
Write a specific query.

**Comment by mschaaf** [comment]
And please point to the code. Thank you.
