### ISSUE TITLE
the "delete initial carts" job deletes about 17k carts on the first run. we should check this, cause it seems this are way too much carts

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#120]
the job deletes about 1k trees, we have to identify these carts and check, if they were actually payed or not

**Comment by Gab0rB** [comment]
disabled the job.
have to clarify with Micha/Christian about the trees in state initial (about 1.3k)

**Comment by Gab0rB** [comment]
SQL to identify this initial state trees:

`select cartId, date, name, (select SUM(_amount) from Tree where _treeId IN(select _treeId from CartItem ci where ci._cart__cartId = cartId)) trees from(
select c._cartId cartId, FROM_UNIXTIME(c._timeStamp/1000) date, u._name name
from Cart c
join CartItem ci on ci._cart__cartId = c._cartId
join User u on u._userId = c._buyer__userId
join Tree t on t._treeId = ci._treeId
where c._cartState = 'INITIAL'
and ci._treeId is not null) a
order by trees desc;`

**Comment by mschaaf** [comment]
Set the DB entries to verified because the carts are valid.
