### ISSUE TITLE
set payment type KK(creditcard) 

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#128]
when paying with creditcard via paypal, the payment type is set to PP.
it should be KK for Creditcard

**Comment by mschaaf** [comment]
@gabor
Why should this be done?
If we pay via paypal should we care how paypal got the money?

**Comment by gabor** [comment]
@Gab0rB is probably the intended github-user :)

**Comment by mschaaf** [comment]
:-) @gabor sorry for the noise and thanks for the correction.

**Comment by mschaaf** [comment]
@Gab0rB Why should this be done?
If we pay via paypal should we care how paypal got the money?

**Comment by mschaaf** [comment]
closed after discussion
