### ISSUE TITLE
tree service image size

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#135]
The image for the treeservice site is too big, it should have the same dimensions like the blog images (DE/EN). 
https://www.iplantatree.org/treeService

**Comment by mschaaf** [comment]
@gerolsteinernaturell both have 986x657. Please tell the sizes you expect and where exactly you see a difference. Please re-open if you have the necessary information. thanks.

**Comment by gerolsteinernaturell** [comment]
Okay, the content area has different widths. This means that the text and image on the tree service page are not flush. 
The content area of the tree service page should be 986 pixels wide (centered).
