### ISSUE TITLE
data protection site (EN)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#141]
It´s not possible to upload the text. Error message: "Oh nein! Beim Hochladen ist ein Fehler aufgetreten, wahrscheinlich ist beim Speichern etwas schiefgelaufen."
https://www.iplantatree.org/privacy

**Comment by mschaaf** [comment]
@gerolsteinernaturell  more details, please. What do you upload where?

**Comment by gerolsteinernaturell** [comment]
this seems to be working now
