### ISSUE TITLE
Widgets problems

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#143]
Mail eines Users:
Mein Wordpress-Widget funktioniert nicht mehr,
da ihr auch die API des Widgets geändert habt. Bisher konnte man über
die UserID die entsprechenden Daten als JSON abrufen, jetzt gibt es
offensichtlich nur noch ein Bild. Ich hoffe wirklich, dass es noch eine
Möglichkeit gibt, die Nutzerdaten irgendwo einzeln abzurufen, sonst
müsste ich das Widget komplett umprogrammieren.

Und noch ein Hinweis für euch: Der Einbettungscode wird nicht richtig
generiert:
> <a href="https://iplantatree.org"><img
> src="https:8081/widget?userName=Vollkornkartoffeln.de&type=white&width=200&height=100"
> /></a>

Bei img src fehlt noch //iplantatree.org:

Zusatz: Ein alt-tag (z. B. "IPAT-Widget") fehlt, was in Wordpress als Fehler angezeigt wird 

Neue Nachricht des Users: Meldet sich einer
eurer Entwickler bei mir? Ich hätte hier gern schnellstmöglich eine
Lösung, da das Wordpress-Widget inzwischen auf einigen Seiten eingesetzt
wird, aber seit eurem Relaunch zeigen alle nur 0 an. Vlt. könnt ihr
vorübergehend die alte API aktivieren oder sowas? Der Code dafür muss ja
noch da sein. Oder könnte ich vlt. mal direkt mit einem Entwickler
sprechen, gern auch telefonieren, ob es vlt. eine andere Möglichkeit
gibt, die Nutzerdaten abzurufen? (Handy-Nummer: xxxxxxxxxxxxx)

**Comment by Gab0rB** [comment]
hier der Link zur API:
https://iplantatree.org:8081/reports/co2/user?userName=[USERNAME]
in meinem Fall wäre das quasi:
https://iplantatree.org:8081/reports/co2/user?userName=Gabor

als ergebnis gibts folgendes JSON-objekt:
{"treesCount":3,"co2":0.08403471909468543}

**Comment by mschaaf** [comment]
@gerolsteinernaturell we are closing it is fixed and clarified
