### ISSUE TITLE
Redeem voucher does not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#148]
Fehlermeldung einer Nutzerin:
ich habe eben versuch meine Gutschein bei euch einzulösen, die ich im Dezember 2018 bekommen habe. Wenn man beim eingeben des Code auf einlösen drückt, erscheint die folgende Fehlermeldung:

"Ein Fehler ist aufgetreten! missing translation: de.CART_TO_GIFT_IS_NULL

https://www.iplantatree.org/gift/redeem

**Comment by Gab0rB** [comment]
der Gutscheincode wäre hier hilfreich.

Anscheinend ist zu dem Code kein Pflanzkorb gemappt.
Wie sollen wir das beheben, wenn das der Fall ist?
Momentan könnte man ja nicht mal einen neuen Planzkorb generieren, da keine Bäume zur Verfügung stehen.

**Comment by gerolsteinernaturell** [comment]
siehe Mail

**Comment by Gab0rB** [comment]
updated column code-id in cart-table, some references were missing.
