### ISSUE TITLE
Evaluate usage of Lombok for generation of getter/setter/... methods

### ISSUE THREAD

**Issue by sebfroh** [Dica-Developer/weplantaforest#15]
This framework needs to be integrated into the run configuration and need to be installed into the existing IDE.
This generated getter, setter, hashCode equals methods.
source: http://projectlombok.org/

*Eclipse setup:*
Run Configuration -> Arguments -> add to VM arguments:
-javaagent:<path to lombok>/lombok.jar
-Xbootclasspath/a:<path to lombok>/lombok.jar

**Comment by mschaaf** [comment]
We already use it.
