### ISSUE TITLE
Umlauts in: Widgets and User names (and probably more)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#153]
1. Feedback from a user: "Das Umlaut-Encoding ist bei der Migration auch kaputtgegangen, alle Umlaute stehen nun als HTML-Entities im Text, Beispiel: „unterst&uuml;tzen“ (Widgets)

2. Some users cannot reset their passwords (users not found). These are users with umlauts in their names (e.g. Möbel, André, Künzel etc.). In the backoffice these also appear only with umlauts. In these cases I renamed the names manually, but for all users this is probably too time-consuming.

**Comment by mschaaf** [comment]
I changed most of the user names. There are still about 10 which need manual changes. Please filter with ";" in the back office user table to find the users that need manual changes.

**Comment by gerolsteinernaturell** [comment]
thanks, done
