### ISSUE TITLE
Editing community plantings

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#154]
If you do a mistake (i. e. wrong location or date) you cannot change it. In addition, plantings can currently have no more than 10 trees. 
1. Users need a possibility to edit and delete their community plantings. 
2. Admins need a possibility to change community plantings, too (e. g. for plantings >10 trees)

direct editing in the selfPlant details page for owner and admin

**Comment by mschaaf** [comment]
@gerolsteinernaturell a fix is committed but we didn't deploy yet. Let's have a look at our next meeting.
