### ISSUE TITLE
password reset problems

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#156]
A lot of users have problems with the pw reset function. Some enter their e-mail instead of their user names. Others don´t know their exakt user names (especially since upper and lower case matters). So I have to do that for them. It would be better, if you can enter your user name OR your e-mail. The info text should be changed:
"Bitte gib deinen Nutzernamen oder deine E-Mailadresse ein. Wir schicken dir dann einen Link, über den du dein Passwort zurücksetzen kannst."
"Please enter your username or email address. We will then send you a link to reset your password."
https://www.iplantatree.org/forgotPassword

**Comment by mschaaf** [comment]
The user is now able to reset the password via username or email.
