### ISSUE TITLE
PW Reset: user names with special characters 

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#160]
When a user with special character(s) tries a pw reset, he gets an error message:
"Ein Fehler ist aufgetreten! Nutzer nicht gefunden."
e.g. user "Bischof + Klein SE & Co.KG"
https://iplantatree.org/forgotPassword

**Comment by mschaaf** [comment]
Dafür haben wir Passwortreset per E-Mail eingebaut. Funktioniert es damit?

**Comment by gerolsteinernaturell** [comment]
ja über die E-Mail funktioniert der Reset, nicht aber über den Benutzernamen
