### ISSUE TITLE
Newest plantings

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#167]
I put trees in the planting basket, clicked Paypal as a payment method and then aborted. Nevertheless they appear now under "new plantings". They have the status "initial". After I deleted the carts, they are gone again.

-> Under "newest plantings" only baskets with the status callback/verified should be displayed.

**Comment by gerolsteinernaturell** [comment]
it's more than just a display problem. Feedback from a user:
"I just tried to order a plant basket with 400,- Euro under my profile "adkonzept". Now I see 2-3 order processes a 400,- Euro, although I only want one. If I enter Paypal as payment method, the order process gets stuck in Chrome on Mac. I ask for urgent clarification, what the status is now and would like to announce as a precaution that it should concern only one procedure to 400, - euro."
Further information: 
- he had cookies activated, no adblocker, tried to pay with Paypal
- After he has closed the Papal window, he sees our page unchanged with the selection of payment methods. 
- The planting basket remains filled.
- he had previously paid somewhere else with PP, so he did not have to enter his PP access data again
- all three trials are displayed as plantings under "Newest plantings", in the back office as "Initial" (deleted them)

**Comment by gerolsteinernaturell** [comment]
Zusatz des Users: "also mit Sepa lief eben alles super. Ich bekomme im Chrome noch ne Fehlermeldung, dass iplantatree.org/p/u/user/image/anonymous.jpg/50/50 mit Error 400 aussteigt. Z.T. werden Inhalte von iplatatree.org ohne und mit www. gezogen – hm."

**Comment by mschaaf** [comment]
The issue is that everytime a user clicks on continue to pay we create a new plant basket.
Only one gets paid and the others are deleted with the housekeeping latest after 4 hours.
The fix will avoid always creating a basket and reduce the housekeeping time to a half hour. We need to count them after going to pay so that no other user can buy them in the meantime.

**Comment by mschaaf** [comment]
The issue with beeing stuck on paypal is only reproducible with an addblocker.

**Comment by mschaaf** [comment]
The fix is deployed on production and staging.
