### ISSUE TITLE
Search for certificates does not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#168]
1 If you enter a certificate number, the entire website disappears (except for the background image). Instead, the planting should be displayed (e.g. 946.50-2).
2. If you enter a certificate number with the hash sign (as specified on the PDF certificate), you will get a message that the certificate does not exist (e.g. #946.50-2). It must be possible to enter the number with the hash sign too because many users use Copy&Paste. 

https://www.iplantatree.org/certificate/find

**Comment by mschaaf** [comment]
Fix is installed on staging and production

**Comment by gerolsteinernaturell** [comment]
Please note point 2 of the ticket: If you enter a certificate number with the hash sign (as specified on the PDF certificate), you will get a message that the certificate does not exist (e.g. #946.50-2). It must be possible to enter the number with the hash sign too because many users use Copy&Paste.

**Comment by gerolsteinernaturell** [comment]
Search with hashtag (#) still does not work.

**Comment by mschaaf** [comment]
please do not reopen already closed issue. reopen new one with examples and description.
