### ISSUE TITLE
Inject a set of example entities on application startup

### ISSUE THREAD

**Issue by sebfroh** [Dica-Developer/weplantaforest#17]
* we should to remove the fake creation of entities.
* on startup some example entities should injected, if no entity of this type exists.

**Comment by mschaaf** [comment]
@jzillmann I will assign this do you as you have the most knowledge about the existing structure.

**Comment by jzillmann** [comment]
Yes will work on that!

**Comment by jzillmann** [comment]
Closing this. Done for treeTypes, Tree's and Users.
Think the next things we should add step by step!
