### ISSUE TITLE
umlauts in bank statements

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#174]
Umlauts are not correctly displayed on the account statements of the Bank für Sozialwirtschaft, e.g. Kevin KC3BCster (instead of Küster) from 6.6.2019, Linda KC3A4mper (instead of Kämper) from 4.6.2019. In the Cards Manager the names are displayed correctly.

**Comment by mschaaf** [comment]
C3BC is small character ü, maybe bank didn't handle UTF-8
We should check the form post.

**Comment by gerolsteinernaturell** [comment]
problem still occurs... e.g. Böhm -> BC3B6hm
