### ISSUE TITLE
Paypal problems

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#175]
We received several donations via Paypal without plant baskets/Plantings being generated.The following are known:
22.5.2019 EINE DER GUTEN 52 Euro Transaktionscode: 10F28711DL033750T 
3.6.2019 EINE DER GUTEN 40 Euro Transaktioncode: 2GV48551NK339620C 
10.6.2019 Michael Kowalik 100 Euro Transaktionscode: 7KN58774R0082972J 
15.6.2019 Zsuzsanna Almasdi 120 Euro Transaktionscode: 4JS99888UP939621J 
19.6.2019: Salon Wohnlich 40 Euro Transaktionscode: 6JJ18363JG1854046 
19.6.2019: Salon Wohnlich 40 Euro Transaktionscode: 6D103939DX5997711
User "salon wohnlich" has said that she has adopted a planting suggestion and then wanted to pay with Paypal. After the payment there was no confirmation, so she did the payment a second time. One of her plantings appeared on her profile but then disappeared.
1. We need to fix that problem (missing plant bags).
2. We need a confirmation like SEPA: popup ("Payment completed successfully! Thank you for your donation.") and the confirmation mail.

**Comment by mschaaf** [comment]
the fix is deployed on prod and staging
