### ISSUE TITLE
faulty voucher

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#176]
The user has received a gift voucher, but cannot redeem it because it has allegedly already been redeemed. Voucher number: XDBA-XWM2-XVGB-PXEE
We've had a similar problem before (general problem?)

**Comment by Gab0rB** [comment]
the code was redeemed by the consignor itself.. the user should see this under the gift overview.
should i reset this to status 'unredeemed' and clear the recipient?

**Comment by gerolsteinernaturell** [comment]
yes please, good idea!

**Comment by gerolsteinernaturell** [comment]
I got her answer. Please reset the code to status 'unredeemed' and clear the recipient.

**Comment by mschaaf** [comment]
The code is valid again.
