### ISSUE TITLE
Paypal problems with different email addresses

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#180]
We currently have two users asking why their plantings are not displayed. In both cases the carts are displayed as anonymous. From one donor I got the answer that he had logged into his account before. 

In both cases the users have different email addresses for Paypal and IPAT.

**Comment by gerolsteinernaturell** [comment]
This has probably nothing to do with the mail addresses. User "TRO" (donation on July 8th) has the same problem and used the same address for IPAT and PP.

**Comment by mschaaf** [comment]
I am going to close this as I can't fix it without steps to reproduce. At the as an admin you could be able to verify her carts.

**Comment by gerolsteinernaturell** [comment]
Another User reports that problem. Maybe it's a result of the caching (?) problem: If you are logged in and open the website in another tab, you are logged out in this new tab. When you close and reopen the browser, you are logged out, too. The users don't notice this and donate anonymously instead of with their username.

**Comment by mschaaf** [comment]
@gerolsteinernaturell please open a new issue for that. For me this sounds like we miss a notice on the cart that the user is going to pay anonymous or not.
