### ISSUE TITLE
default profile images

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#183]
On newer (?) profiles the default image is not displayed, e. g.:
https://iplantatree.org/user/Anjaknoll
https://iplantatree.org/user/Denitsa%20Harizanova
![default_user](https://user-images.githubusercontent.com/12950263/61960093-26730100-afc5-11e9-8bd9-e8d79ffe7253.jpg)
Older profiles do not seem to have the problem.

**Comment by mschaaf** [comment]
Get user details query sets `·COALESCE(user.imageName,·'anonymous.jpg'),`

**Comment by mschaaf** [comment]
@gerolsteinernaturell please check if this is still valid

**Comment by Gab0rB** [comment]
this seems to be fixed with 154b11ab1403cde48a24467c4718c4bc2ea1f2d3
