### ISSUE TITLE
Quadratmeter-Projekt

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#184]
Wir brauchen eine Möglichkeit, Projekte für Flächen anzubieten. So können wir Spenden für den Flächenkauf akquirieren. Das vor allem dann wichtig, wenn wir kein anderes Projekt online haben. Was wir dazu benötigen: 
1. Separater Quadratmeter-Zähler (also unabhängig vom Baumzähler), der im Frontend erstmal nicht angezeigt wird
2. Flächen-Projekte werden wie normale Projekte angelegt mit Bild, Beschreibung, Produkt… („Quadratmeter“ bzw. „square meters“)
3. Projektseite: Wie bei anderen Projekten nur mit dem Unterschied, dass 
a) statt der OSM-Karte eine Grafik angezeigt wird (liefern wir nach), diese Grafik wird dann auch auf der Startseite angezeigt
b) unten bei den Rankings „Beste Teams“/“Best teams“ (wie bisher), in der Mitte „Beste Spender“/„Best donors“ und rechts „Neueste Spenden“/“Newest donations“
c) Beschriftung neben Kuchendiagramm (Projektseite oben): 100% „gespendet“/“donated“, 4.323 „Quadratmeter“/“Square meters“
4. Quadratmeter-Anzeige im Profil der Nutzer anzeigen: „Fläche gespendet“ bzw. „Area donated“
5. Quadratmeter-Anzeige im Profil der Teams anzeigen: „Fläche gespendet“ bzw. „Area donated“
6. Man sollte Quadratmeter und Bäume zusammen in den Pflanzkorb legen können

**Comment by IPAT1** [comment]
Hier meine Definition zum Flächentyp:
dieser sollte folgende Parameter haben: 
Quadratmeter / Squaremeter
Bodenart (Sand, Schluff, Ton, Lehm, etc. ) / Soiltype  (sand, silt, clay, loam)


Der Boden / Soil als Shop Item sollte folgende Parameter haben:
Anzahl
Preis pro Einheit

**Comment by gerolsteinernaturell** [comment]
maybe in the future
