### ISSUE TITLE
gift codes

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#188]
A user told us, that his gift codes (he has 15-20 of them) don´t work. He now wants to give them his customers.
User: https://www.iplantatree.org/user/Wortmann%20AG
Example code: ACWM-SBAK-EEGH-URTA

**Comment by gerolsteinernaturell** [comment]
here is a screenshot from another user:
![screenshot](https://user-images.githubusercontent.com/12950263/65974169-c6895280-e46c-11e9-9af5-43bf54c0add2.jpg)

**Comment by mschaaf** [comment]
@gerolsteinernaturell The codes you send me should now work, but it affects all codes from them. We have to write an upgrade script to reconnect the codes with the cart.
