### ISSUE TITLE
gift codes do not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#191]
some codes from user "Autohaus Kuhn+Witte" do not work (example see attached), they tried that yesterday.
![fehlercode](https://user-images.githubusercontent.com/12950263/68212998-06e36f80-ffdb-11e9-95cd-d7a0f0949657.JPG)
Set to important too, they want to start a campaign.

**Comment by mschaaf** [comment]
The fix is already installed on 2019-11-05 at about 8pm. Please try again.
