### ISSUE TITLE
unintentionally anonymous donations

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#196]
Several users unintentionally donate anonymously. Maybe it's a caching problem: If you are logged in and open the website in another tab, you are logged out in this new tab. When you close and reopen the browser, you are logged out, too. The users don't notice this and donate anonymously instead of with their username.

The problem is a lot of work because the users can't create certificates and I have to plant for them via backoffice. I'm not sure if they will receive correct donation receipts in those cases (under "Carts" the name fields are empty).

**Comment by mschaaf** [comment]
@gerolsteinernaturell 

1. We have a message on the cart that states you are anonymous and not logged in. Is it too small? Is the user not understanding it?

2. Should we no longer allow anonymous payment?

How should we solve it?

**Comment by gerolsteinernaturell** [comment]
Anonymous donation is important. However, it would be helpful if you stay logged in after logging in - even with new tabs or a restart of the browser (apart from private mode, of course). This is what users are used to from other websites as well.

**Comment by mschaaf** [comment]
@gerolsteinernaturell Could you reproduce it? I can't.

Our session cookie is valid for a very, very long time and is not invalidated on browser/tab close. I know that because I regularly start my browser new and I checked the date of the cookie.
This makes me think that the user has set up their browser so that it destroys the session on tab or browser close.
Anyways if you can tell me the browser with that it happens and the settings I could say it more definitely.

**Comment by gerolsteinernaturell** [comment]
I have tested differerent settings in Firefox. You are right, without strict privacy settings (deleting cookies) it works. I could only reproduce this by clicking with the middle mouse button on the small buttons in the header, the 3 icons on top without text and the 3 one with text "Plant Yourself", "Plant Online", "Treeservice"). In that new tabs you are logged out. 

Because some users had the problem, we should do something:
1. Link the mentioned links so that you stay logged in in the new tab.
2. Replace the note in the planting basket.
Bold and with exclamation mark: 
"Important: You are not logged in!"
Below (normal text):
"There are less functions available, when you plant anonymously. You can only create certificates and vouchers as a registered user." 

DE:
"Wichtig: Du bist nicht eingeloggt!"
Below (normal text):
"Wenn du anonym pflanzt, stehen dir weniger Funktionen zur Verfügung. Nur als registrierter Nutzer kannst du Zertifikate und Gutscheine erstellen."

I hope that this will be clearer for the users. In the current German hint is a typo. And everyone gets receipts, therefore we have to change the hints anyway.
