### ISSUE TITLE
error message "Verbindung zur Spendenbank nicht möglich"

### ISSUE THREAD

**Issue by Grimmwicht** [Dica-Developer/weplantaforest#200]
The error message "Verbindung zur Spendenbank nicht möglich" appears, when nothing is selected in the drop down *salutation*. Well, apparently it won't connect to the bank without getting all needed infos from the donator, so the error message is kind of right, but a useful error message for the donator would be: "Please fill out all forms neccessary".

**Comment by mschaaf** [comment]
Thank you for your report we will have a look at it.

**Comment by mschaaf** [comment]
Hej @Grimmwicht, OI had a look at this issue and I could pay without the salutation. So in your case, I would say it was really an issue on the bank side and only a coincidence that it worked on a retry with the salutation set. Anyways after reviewing the code, we could found a another small issue I will fix it with this issue. Thanks for your help.
