### ISSUE TITLE
scrolling through plantings on team pages

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#231]
On team pages there is no left arrow when you scroll (right) through the plantings. So you can´t go back.
Example: https://www.iplantatree.org/team/Wortmann%20AG%20%2F%20Terra%20Partnerprogramm (link does not work due to blank spaces, another topic)

**Comment by mschaaf** [comment]
fixed with 4019def08e8b428b5ef34ccc82b5bdb37abbdfa6
