### ISSUE TITLE
Paypal problem

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#250]
A user wanted to pay with Paypal and reported the following problem:
"Just donated 10 trees. Unfortunately the payment via PayPal did not work. After login the PayPal window closed and it was not possible to continue. 
After he logged in via PayPal and paid, nothing else happened. He tried again and then via SEPA (which worked). The amount was debited twice by Paypal without us or him receiving a confirmation mail. Paypal cancelled the bookings by itself.

**Comment by mschaaf** [comment]
not reproducible
