### ISSUE TITLE
events with different tree species

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#252]
I tried to create an event with two tree species (100 codes à 3 trees). Insteat of 3 trees I got 5 per code. 

Then I did the same with one tree species and it worked. We should be able to create codes with more than one tree species.

**Comment by mschaaf** [comment]
fixed with commit https://github.com/Dica-Developer/weplantaforest/commit/b0b04f8dd0542945d17b9eb961c784f4776beb62
