### ISSUE TITLE
problems creating donation receipts

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#253]
A user gets the following message when trying to create a receipt:
ERROR
Failed to load PDF document
user: https://www.iplantatree.org/user/varo_talentry

**Comment by gerolsteinernaturell** [comment]
Another user reports this problem: https://www.iplantatree.org/user/teleropa
But in both cases they donated less than 8 weeks ago. So probably the PDFs are displayed before they have been created.

**Comment by mschaaf** [comment]
Please ask for more info:
* receipt id
* URL
* more error details
* steps to reproduce
