### ISSUE TITLE
carts grid bugs

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#255]
1. When you check the checkbox in column "SQ", you first have to scroll to see any difference. You should see changes immediately.
2. When you change the status of a cart, e. g. from "callback" to "verified", and then click on "Lade Pflanzkörbe" (filter "Callback" set), then the first cart in the grid is set to "verified".

**Comment by mschaaf** [comment]
1. point done
2. second point should be handled similar to first by changing the html element instead of creating new elements
