### ISSUE TITLE
Combine coverage files of BE and UI tests to send to coveralls

### ISSUE THREAD

**Issue by JayGray** [Dica-Developer/weplantaforest#26]

**Comment by mschaaf** [comment]
BE is already done see the front of the repo or this url https://coveralls.io/r/Dica-Developer/weplantaforest?branch=master

**Comment by mschaaf** [comment]
Here is an example how to do it https://github.com/ben-manes/caffeine/blob/master/build.gradle
and I would like to implement it, but how do I generate coverage reports for the UI tests?
