### ISSUE TITLE
problems creating gift vouchers

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#263]
User Tante Emmas Bruder reports on 27th october:
"Leider lässt sich nur 1 Gutschein für 1 baum erstellen, danach kommt "Fehler, doppelte Spende" 
Question: Welchen Browser und welches Betriebssystem verwenden Sie? Zum Ablauf: Sie haben einen Gutschein erstellt und der Versuch einen zweiten zu erstellen führte zur genannten Fehlermeldung? Haben Sie dafür oben im Browser auf "zurück" oder wo haben Sie geklickt?
his answer:
"Ich habe es jetzt mit Firefox und Edge getestet. In beiden Fällen kam es zu dem Fehler, wenn ich versucht habe die gleiche Anzahl an Bäumen als Gutschein zu kaufen
Habe folgende Gutscheine bisher gekauft:
4 Bäume: OK
2 Bäume: OK
1 Baum: Ok
1 Baum: ein Fehler ist aufgetreten: Doppelte Spende
Ich habe nicht die Zurück-Taste benutzt, bin immer über Mein Wald-> Gutscheine-> Gutschein erstellen"

**Comment by mschaaf** [comment]
Bank does not allow the same donation amount in a short period.

**Comment by mschaaf** [comment]
@gerolsteinernaturell please talk to the bank.

**Comment by gerolsteinernaturell** [comment]
bank reply: 
"Aus Sicherheitsgründen werden Doppelspenden blockiert. Hier prüfen wir folgende Parameter: OID, Betrag, Zahlungsart, Vorname, Nachname, Email-Adresse, Strasse, Verwendungszweck. Wenn diese Parameter identisch sind, geben wir den u.g. Fehler aus.  Hiermit soll sichergestellt werden, dass nicht unbeabsichtigt derselbe Datensatz mehrfach abgeschickt wird.  
Wenn es also gewünscht wird, denselben Betrag mehrfach zu spenden, müssen andere Parameter geändert werden. 

Im Falle der Spende von Frau E. vom 8.11.2020 hat diese Prüfung keine Doppelspende identifiziert, da sich die übertragenen Daten unterscheiden. Bitte vergleichen Sie hierzu die eingegebene EMail-Adresse. Sie finden alle Spenderdaten im BFS NetTOOL unter Menüpunkt Spendendaten > Spendendatenexport & Löschfunktion monatsweise. Bitte beachten Sie, dass wir die Daten aus Datenschutzgründen nur 100 Tage speichern dürfen."

**Comment by mschaaf** [comment]
made the verwendungszweck unique
