### ISSUE TITLE
sending receipts not possible

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#266]
It is currently not possible to send donation receipts for verified donations. Error message:
"Es ist ein Fehler aufgetreten! Beim erzeugen und versenden der Quittung ist ein Fehler aufgetreten:undefined"
https://www.iplantatree.org/cart-manager

**Comment by mschaaf** [comment]
Error message from backend: `Receipt already exists.`
Seems the resend button is not rendered.

**Comment by mschaaf** [comment]
Already fixed.
