### ISSUE TITLE
Old reports API gone?

### ISSUE THREAD

**Issue by Grimmwicht** [Dica-Developer/weplantaforest#316]
Hi folks,

some time ago I wrote a plugin for Wordpress to save server requests and make it easily translateable: https://wordpress.org/plugins/i-plant-a-tree/ . It worked well in the last years but stopped working recently.

It uses the old reports API to get a json with tree count and savings: https://iplantatree.org/reports/co2/user?userName=vollkornkartoffeln.de . This, however, seems to be disabled now – the script just hangs until a network timeout occurs.

So was this API just moved or is it gone for good?

**Comment by mschaaf** [comment]
The URL is prefixed with `/p/u/`. For your example, it should be now `https://iplantatree.org/p/u/reports/co2/user?userName=vollkornkartoffeln.de`

**Comment by Grimmwicht** [comment]
Wonderful, thanks, that worked. And what would be the equivalent for a team?

**Comment by mschaaf** [comment]
It's possible to get the team related information via this REST call `https://iplantatree.org/p/u/team?teamName=<team name>`

**Comment by Grimmwicht** [comment]
Yeah, that did the trick. Many thanks.
