### ISSUE TITLE
Making Cart manager more user-friendly

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#328]
- reduce "PLZ" column width
- change the arrangement of the columns (from left/important to right/unimportant): Status wechseln, Aktion, SQ, Details, Zahlungsart, Preis, Erstellt am, User, Vorname, Nachname, Unternehmen, Straße, Ort, PLZ

**Comment by Gab0rB** [comment]
obsolete cause there is a new cart-manager in progress
