### ISSUE TITLE
Liberate Image handling functionality out of main code

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#36]
Idea is to create a module/service for image processing/handling.
**resize/scale**
* gets a stream and returns a stream with the processed result

**save**
* gets a stream and returns an identifier

**load**
* gets an identifier returned from save and returns a stream

**Comment by Gab0rB** [comment]
Should i move the ImageController to module common and change this to a runnable application now?
So we can create there a central imageFolder-structure to handle all images.
The controller would have several functions to root the calls to the demanded folders and get the asked image. Same for the upload.

e.g. : 
- user-module calls /image/projects/{projectName}/{imageName} and gets the image from the ImageController, which would be passed through this user-controller method back to the frontend.

**Comment by mschaaf** [comment]
Please not a seperate  application. Lets add a rule: We create an apllication only for parts that can run with there own DB. Image processing is part of several entities like projects and articles so no own applciation IMHO.

**Comment by Gab0rB** [comment]
Ok, i get it now. I was a little confused about the word module.
I just finished the upload funtionality, next i will try to implement the image functions project- and article specific for seperate folders with seperate urls.
