### ISSUE TITLE
carts area

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#364]
1. top dropdown: please rename "Cartstates" to "Status"
2. Date range: Spacing between dates and hyphen inconsistent
3. dropdown to change status with a single click (currently only possible by double-clicking + clicking again)
4. dropdown to change status: Remove "Cartstate"
5. please increase height of the cart area a bit (= more rows without scrollbar)

**Comment by Gab0rB** [comment]
render state-dropdown initially
