### ISSUE TITLE
Explore the storing of the test results in a git repo

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#46]
See this idea from the relevant travis forum https://github.com/travis-ci/travis-ci/issues/532#issuecomment-5946521

There also some documentation around it
https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by jzillmann** [comment]
So after reading the links...
- there is still no out-of-the-box functionality in travis to upload build artifacts to something other then s3
- there is a project which helps pushing build artifacts to github pages: https://github.com/IcecaveStudios/woodhouse
