### ISSUE TITLE
Carousel not shown on index.html

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#48]
If you open the index.html there's no carousel to see.

ErrorMessages:
Error this.state.slides.map is not a function - Teaser.js? (Zeile 50)
TypeError: $next[0] is undefined - bundle.... > eval (Zeile 147, Spalte 7)

Screenshot:
![no_carousel](https://cloud.githubusercontent.com/assets/18173646/15534186/f83eeab2-2267-11e6-94a1-3793ee3433ee.png)

**Comment by mschaaf** [comment]
I cann also reproduce with firefox

**Comment by mschaaf** [comment]
@Gab0rB you changed the backend result. Now its again under content and before it was directly a array. I guess the paging introduced the change.
