### ISSUE TITLE
overview of all active projects

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#50]
the url to access the data is following: **/reports/activeProjects?page=0&size=10**

the idea is to show them like this: **https://www.ecocrowd.de/entdecke/**
perhaps more like a scrollable bar from left to right, if there are more than 3 active projects instead of displaying them on top of each other like in a table

**Comment by mschaaf** [comment]
If we have designs we can create issues on how it looks like. Currently the page exists and shows all the projects.
