### ISSUE TITLE
warning.js?8a56:44 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Projects`. See https://fb.me/react-warning-keys for more information.

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#52]
warning.js?8a56:44 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Projects`. See https://fb.me/react-warning-keys for more information.

The application should work without these warnings.

**Comment by mschaaf** [comment]
@JayGray Do you know what this means? This happens on URLs /,  /explore

**Comment by Gab0rB** [comment]
to solve this issue there has to be add the key prop to iterated html elements, e. g.:

  {this.props.slides.map(function(slide, **index**) {
            var activeItem = 'item';
            if (0 === index) {
              activeItem = 'item active';
            }
            let imageUrl = 'http://localhost:8081/project/image/' + projectName + '/' + slide.imageFileName + '/1140/1140';
            return (
              <div className={activeItem} **key={index}**>
                <img src={imageUrl} width="1140" height="400" alt={slide.imageFileName}/>
                <div className="imageDescription">
                  <span className="date">
                    <i>{moment(slide.date).format("DD.MM.YYYY")}</i>&nbsp;/&nbsp;</span>
                  <span className="text">{slide.description}</span>
                </div>
              </div>
            );
          })}

https://coderwall.com/p/jdybeq/the-importance-of-component-keys-in-react-js
