### ISSUE TITLE
creating new projects only possible if the name is entered beforehand 

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#580]
A new project is only saved if the name is entered beforehand and no other field is filled in. You can only edit the project after saving it. It would be more intuitive if you could edit the project directly.

**Comment by Gab0rB** [comment]
hhm thats not true

i saved a project without the name entirely, added checkboxes for "sichtbar" and "aktiv" and also added a tree to the project and everything was saved as i entered
