### ISSUE TITLE
arrange footer links

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#585]
Column 1
Rankings (instead of "Bestenliste")
Zahlen & Fakten (instead of "Fakten")
Finanzen

Column 2
Über uns
Partner
Auszeichnungen

Column 3
FAQ
Kontakt
Newsletter
 
Column 4
Impressum
Datenschutz
AGB

**Comment by Fiehra** [comment]
agb page missing and awards page missing,  remove press page

**Comment by Fiehra** [comment]
also faq missing
