### ISSUE TITLE
accessing ImageController 

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#59]
I implented an ImageController now.
The access urls are following:

**/image/{imageName}** or **/image/{imageName}/{width}/{height}**

The resizing of the images works only for same proportions.
You can access other proportions in the url, but the pic will scale only till the max value of one of the two parameters is reached.
So if you have a pic at 300X200, you cann access 600x600, but the size will be 600x400, if you access 600x300 the size will be  450x300. 
So there is no stretching of pics available atm. I wasn't sure if we need this.
(And it wouldn`t be just a oneLiner like the functionality now ;-) )

There are some pictures available now, e.g. test.jpg, project1.jpg,... till project10.jpg

The url **/reports/activeProjects?page=0&size=10** delivers now a variable called **projectImageFileName**, where you get the name of the mainImage of a project, so there can be included some pics now on the explore page(the databasePopulator is also extended with the delivered imageFileNames).

I also included a list of imageData(with title, description, imageFileName and date) under 
**/projects/search/name/extended/{projectName}** for the detailed project informations.
There you can access the data under **$.images[0].title** and so on.
For the already existing variables you have to add the prefix **$.projectReportData.**.

Later we can replace this url with **/projects/search/name/<projectName>**, but now i wanted to run them parallel, cause of the changed JSON-format.

Please share your opinion, if you had time for review and trying this out.

**Comment by mschaaf** [comment]
I would liek to move the URL under a URL called /projects/<project id/name>/image/<image name>/...

So the image name does not need to be unique and we can easily check on the project and validate the request.
