### ISSUE TITLE
startpage: The projects are not shown on the map.

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#600]

**Comment by Gab0rB** [comment]
![image](https://github.com/Dica-Developer/weplantaforest/assets/18173646/fa1c3145-d155-4fbe-a111-b21d75321cc1)


dont know if this makes really sense... on the image above theres the area for Kalbe right over the g of Wolfsburg

**Comment by Gab0rB** [comment]
![image](https://github.com/Dica-Developer/weplantaforest/assets/18173646/d4f8f11a-de70-435c-b644-f7d9c3640ec1)

**Comment by Gab0rB** [comment]
![image](https://github.com/Dica-Developer/weplantaforest/assets/18173646/efa1e63e-97ee-40d0-baf9-22e835ddd97b)
