### ISSUE TITLE
change overview in preselected planting

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#606]
For the overview of the suggested trees we need a line like in the old application (in bold) in that order:
Tree species Price / Item 
Amount 
Project 
Subtotal (should be on the right)

https://www.iplantatree.org/staging/plant

**Comment by Fiehra** [comment]
improved layout. changed order of headers

**Comment by gerolsteinernaturell** [comment]
1. Please add the line as described above.
2. We should use more of the width. The suggested trees table should be wider, e.g. like the slider above.

**Comment by Gab0rB** [comment]
add margin between image and tablerow
