### ISSUE TITLE
"Hier pflanzen" button on single project page

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#616]
Currently the button leads to https://www.iplantatree.org/staging/plant. 
When you click on the button, however, the project should be preselected (as in the old application). 

https://www.iplantatree.org/staging/project/Zollhaus%20VIII

**Comment by Fiehra** [comment]
alternative idea: only button routes to normal planting page.
clicking on trees will open explore page instead. trees are not dynamic

**Comment by Fiehra** [comment]
instead when clicking on tree -> put 5 trees into plantbag
<br>
check if tree available -> only take trees from active projects
<br>
randomly show trees from active projects
