### ISSUE TITLE
Eigene Pflanzung erstellen: generic error message

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#624]
You can leave everything blank (no image, no description, no map entry) to generate a planting. It just doesn't work if you don't choose a tree species.
error message: ein unerwarteter Fehler ist aufgetreten

To create a planting, the user must provide all the information:
Image, number of trees, Planting date, Tree species, Location

If not, the user should get a meaningful message (e.g. "Bitte gib den Standort der Pflanzung an.")

**Comment by Fiehra** [comment]
maybe adjust error message as it is kinda generic

**Comment by Fiehra** [comment]
description not shown anywhere.
