### ISSUE TITLE
profile: Spendenquittungen

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#632]
- We should use the full width of the website and display 2 or 3 tables next to each other.
- Insert a line above the tables: Date, Number, Download
- The download icon should be placed a little higher.

**Comment by Fiehra** [comment]
add mat table

**Comment by gerolsteinernaturell** [comment]
There is still only one column, yan't we put two next to each other?
Please do not call the number "Rechnungsnummer", but "Nummer" (resp. number in EN) as described above.
