### ISSUE TITLE
backoffice projekte: error when creating project without selecting tree species

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#639]
When I want to create a project and do not select a tree species, a long error message appears. It would be better if a tree species (default?) is preselected.

Error message:
 "org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : org.dicadeveloper.weplantaforest.admin.project.ProjectArticle.treeType -> org.dicadeveloper.weplantaforest.admin.treeType.TreeType; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : org.dicadeveloper.weplantaforest.admin.project.ProjectArticle.treeType -> org.dicadeveloper.weplantaforest.admin.treeType.TreeType"

**Comment by Gab0rB** [comment]
default tree shouldnt be used i thought, so setting it as default is not quite optimal.

i added an error message to supress the save to the backend when there is an error:

![image](https://github.com/Dica-Developer/weplantaforest/assets/18173646/08ce3582-a084-4d40-ae8f-22e51fff12b2)
