### ISSUE TITLE
backoffice projekte: uploading images does not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#640]
error message:
"org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : org.dicadeveloper.weplantaforest.admin.project.ProjectArticle.treeType -> org.dicadeveloper.weplantaforest.admin.treeType.TreeType; nested exception is java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: Not-null property references a transient value - transient instance must be saved before current operation : org.dicadeveloper.weplantaforest.admin.project.ProjectArticle.treeType -> org.dicadeveloper.weplantaforest.admin.treeType.TreeType"

**Comment by Gab0rB** [comment]
it works

the error is someting about not saved treeTypes, i will look into that
