### ISSUE TITLE
add cookie popup

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#648]

**Comment by Fiehra** [comment]
cookie research germany:
https://www.bmuv.de/fileadmin/Daten_BMU/Download_PDF/Verbraucherschutz/cookie_guidelines_bf.pdf

1.1

**Comment by Fiehra** [comment]
Cookie-Banner sollten so gestaltet sein, dass Verbraucher*innen entscheiden können, ob sie
der Speicherung von Cookies auf ihrem Gerät und der Verarbeitung ihrer Daten durch ein
Unternehmen oder eine Organisation zustimmen. Das bedeutet, dass Cookie-Banner nur
dann verwendet werden sollten, wenn ein Unternehmen oder eine Organisation Informationen
sammeln und verarbeiten möchte, die gesetzlich eine Einwilligung erfordern.
Wenn dagegen die Einwilligung zu Cookies bei der Nutzung einer Website oder eines Inter-
netdienstes gesetzlich nicht erforderlich ist, ist kein Cookie-Banner notwendig. Verbrau-
cher*innen sollten jedoch auf andere Weise über die Verwendung dieser Cookies informiert wer-
den, z. B. in der Datenschutzerklärung. Wenn dagegen zusätzlich zu Cookies, die eine Einwilli-
gung erfordern, Cookies verwendet werden, die keine Einwilligung benötigen, können Informatio-
nen über die Cookies bereitgestellt werden, die keine Einwilligung erfordern, auch im Cookie-
Banner bereitgestellt werden.

**Comment by Fiehra** [comment]
if accept

display paypal

if declined

hide paypal and add snackbar that paypal payments are disabled
