### ISSUE TITLE
project-overview-tile image is too blurry

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#661]
increase width/height properties
first one is width, second one is height

**Comment by gerolsteinernaturell** [comment]
The image quality should not be the problem, resolution of the project images is 1140x570. The scaling is wrong: 508,6x500 px

**Comment by gerolsteinernaturell** [comment]
the blog images are blurry too

**Comment by Fiehra** [comment]
will be solved with #830

blog already fixed
