### ISSUE TITLE
breadcrump navigation

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#678]
1. Please add breadcrump navigation to this page (Startseite / Fläche anbieten):
https://www.iplantatree.org/staging/offerArea
2. Change breadcrump navigation on German policy page from "privacy" to "Datenschutz"
https://www.iplantatree.org/staging/privacy

**Comment by Gab0rB** [comment]
add underline to offerArea breadcrumb navigation
