### ISSUE TITLE
adjust trees when switching to indivual tab on planting page

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#685]
The new planting page is more complicated than the old one (3 options for planting with three headlines).

Suggestion (we can talk about that beforehand if it´s time-consuming):
Add "individual" to the slider on the right next to 100 trees (like the "individual-button on the old website). When you select this setting, the table with the tree suggestions disappears and the table with the available trees shows up. In this way we can get rid of the corresponding line/dropdown ("Bäume auswählen - Hier entscheidest du selbst, welche Bäume du wo pflanzen möchtest.")

Then we have to shorten the line: "Wieviele Bäume möchtest du pflanzen? Wir erstellen für dich einen passenden Pflanzkorb." Better: "Wieviele Bäume möchtest du pflanzen?"
https://www.iplantatree.org/staging/plant

**Comment by Gab0rB** [comment]
try out adding 3 tabs for all planting types(proposal/individual/selfplant)

**Comment by gerolsteinernaturell** [comment]
1. Please use the coupons tabs (user profile)
2. The trees in the first tab (tree suggestion) should be adopted when switching to the second tab (individual).

**Comment by Fiehra** [comment]
adjust trees in custom page
