### ISSUE TITLE
team profiles layout

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#691]
- Please add a horizontal line under the logo and a vertical line in the middle (so that theses profiles look similar to the user profiles)
- change the label "Registriert seit" to "Gegründet"

**Comment by Gab0rB** [comment]
add vertical line

**Comment by Fiehra** [comment]
only display vertical  on team page

**Comment by Fiehra** [comment]
remove vertical line from details on profile page
