### ISSUE TITLE
Connect entity TreeType with Tree and expose TreeType with rest call for a tree

### ISSUE THREAD

**Issue by sebfroh** [Dica-Developer/weplantaforest#7]

**Comment by mschaaf** [comment]
Hej @sebfroh maybe @jzillmann could provide you with all the current entities so that we can implement something works with the old schema.

**Comment by sebfroh** [comment]
Hey @mschaaf , i have the old schema available. Lets talk in person. This is my first draft. There is room for improvement :)

**Comment by jzillmann** [comment]
@sebfroh oh i could you provide the old hibernate entities if that helps!

**Comment by sebfroh** [comment]
Hi @jzillmann, this would help. I need some more domain specific knowledge to understand the existing schema. I will prepare some questions for you. :)
