### ISSUE TITLE
backoffice: project trees

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#712]
When I created the test project, I added beeches four times. It would be great if each tree species could only be added once.

https://www.iplantatree.org/staging/backOffice2022/projects

**Comment by Gab0rB** [comment]
![image](https://github.com/Dica-Developer/weplantaforest/assets/18173646/c306a8dc-79ab-4954-b3ab-6f5e5794be0b)
