### ISSUE TITLE
sort faq by number in title and split view in 2 parts

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#721]
according to old FaqView.js

something like:

`  sortByNumberIntTitle(data) {
    for (let entry of data) {
      let index = entry.title.substring(0, entry.title.indexOf('.'));
      if (index == '') {
        index = 0;
      }
      entry.index = parseInt(index);
    }
    data.sort(function(a, b) {
      return a.index > b.index ? 1 : b.index > a.index ? -1 : 0;
    });
  }
`

**Comment by gerolsteinernaturell** [comment]
Please do the same with the finances, so that it is sorted by year (Current years above, old years below).

https://www.iplantatree.org/staging/finances

**Comment by Gab0rB** [comment]
mobile has some issues
faq - wrong anchor points
finances - not shown at all
