### ISSUE TITLE
startpage: projects are missing on the map (e.g. Berlin projects)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#727]
https://www.iplantatree.org/staging/

**Comment by Gab0rB** [comment]
at the moment there is no active project near berlin 
only the following ones:
- Test
- Zollhaus VIII
- Zollhaus VII
- Drage
- Merseburg III
- Merseburg II
- Merseburg I
- Ramsenberg 
- Zollhaus VI
- Zollhaus V

none of these are near Berlin and all are shown up on the map
some of them are overlapping, cause their location is next to each other

**Comment by Gab0rB** [comment]
closed, cause clarified
