### ISSUE TITLE
user profile: table layout

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#731]
After consultation with Micha: The overviews of the donation receipts and certificates should look the same as the gifts overview with tables next to each other. The main thing is that the three are standardised.

TBD: What to do if the tables become too long? We can, for example, display a maximum of 10 lines and make the next 10 expandable.

**Comment by Fiehra** [comment]
added paginator to all tables

what we could do is we could merge donation table and certificate table by using tabs
