### ISSUE TITLE
rankings: change colors of progress bars depending on status

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#734]
1. Change the button: "last year" to the left (because it is default), "total" to the right side
2. button colours not dynamic, but only change the colour of the progress bar: When clicked in total, the bars turn green. If Last year was selected, the bars turn dark brown.

**Comment by Fiehra** [comment]
looks weird if button colors dont change. maybe hover effect is needed or just leave the active toggle effect.

bar colors now change depending on timespan
