### ISSUE TITLE
improve plant tree component info text (homepage)

### ISSUE THREAD

**Issue by Fiehra** [Dica-Developer/weplantaforest#744]
reference trees on right and explain what to do

**Comment by Fiehra** [comment]
improved text, waiting for feedback

**Comment by gerolsteinernaturell** [comment]
Please use this text: 
Headline: Bäume pflanzen 
Text: Wähle eine Baumart, um sie direkt zu pflanzen. Wenn du auf den Button unten klickst, hast du zusätzliche Optionen.
