### ISSUE TITLE
add header to proposal row in individual page

### ISSUE THREAD

**Issue by Fiehra** [Dica-Developer/weplantaforest#751]

**Comment by Fiehra** [comment]
![projectname in row only 1 header](https://github.com/Dica-Developer/weplantaforest/assets/45260245/262ff3d8-15eb-4d4f-8ba4-d10096f7ee2a)

![projectname in header](https://github.com/Dica-Developer/weplantaforest/assets/45260245/3b27a951-7874-4e07-afa8-1ec747cc1926)

**Comment by Fiehra** [comment]
i feel like 2nd screenshot looks better. mobile is unchanged

**Comment by gerolsteinernaturell** [comment]
Thanks! Please the first one, so the layout is similar to the proposal tab

**Comment by gerolsteinernaturell** [comment]
OK, I find the second better too
