### ISSUE TITLE
wrong website language

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#755]
On mobile and desktop the website is in English (when I am not logged in), but my browsers are German 
-> only set to English if browser language is definitely not German

**Comment by Gab0rB** [comment]
mobile firefox(ger) --> shows english
mobile chrome(ger) --> shows english

**Comment by gerolsteinernaturell** [comment]
the problem still exists (a user has noted that too). As long as the browser switch does not work, please remove it. Until then the website must be in German, if you need English you have to change it manually in your profile.
