### ISSUE TITLE
user profile: unexpected behaviour when password is saved in browser (chrome)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#762]
When I click on the edit-pen, the Profile-Edit page open & I immediately get the message "Nach Änderung des Passwortes musst du dich neu anmelden!". The input field for the password is highlighted. 

This should only be the case when you click in the input field to change the password.

**Comment by Fiehra** [comment]
cant reproduce this on mobile or laptop chrome
