### ISSUE TITLE
implement SSR for SEO

### ISSUE THREAD

**Issue by Gab0rB** [Dica-Developer/weplantaforest#768]

**Comment by Fiehra** [comment]
https://blog.logrocket.com/server-side-rendering-angular-16/

**Comment by Fiehra** [comment]
updating to angular 16 might be helpful for this

**Comment by gerolsteinernaturell** [comment]
Our ranking is not only poor in the organic search, but also in the adverts (Google cannot find any content -> ads are not displayed).

**Comment by Fiehra** [comment]
update to v17 angualr 17 has native SSR included

**Comment by Fiehra** [comment]
https://stackoverflow.com/questions/77582598/error-in-angular-server-side-rendering-ssr-with-ngx-leaflet-referenceerror

some packages 3rd party are throwing errors because of window usage in node environment

**Comment by Fiehra** [comment]
https://stackoverflow.com/questions/58080301/how-to-use-angular-universal-with-leaflet

**Comment by Fiehra** [comment]
https://stackoverflow.com/questions/77534244/local-storage-is-not-defined-in-angular-17

for local storage

also needs to be encapsulated in its own service

**Comment by Fiehra** [comment]
version update: angular v18

**Comment by Fiehra** [comment]
:cry: might need to refactor to standalone components to make leaflet work

**Comment by Fiehra** [comment]
https://github.com/sutin1234/angular-17-SSR--ngx-translate/tree/main/src

example repo  with standalone components and SSR

**Comment by Fiehra** [comment]
https://gitlab.com/fiehra/aeye


for leaflet SSR
