### ISSUE TITLE
add newsletter text to registration confirmation mail

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#774]
"Tipp: Mit unserem Newsletter erfährst du als Erstes, wenn neue Projekte online gehen. Du kannst das Abo natürlich jederzeit kündigen. Hier geht es zur Anmeldung: https://www.iplantatree.org/newsletter"

"Tip: With our newsletter, you'll be the first to know when new projects go online. You can of course cancel your subscription at any time. Click here to register: https://www.iplantatree.org/newsletter"

**Comment by Fiehra** [comment]
move text to registration confirmation page -> useractivation page
