### ISSUE TITLE
backoffice "Projekte -Bilder": updating documentation

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#776]
1. When I try to edit the description of an already uploaded image, I get a success message after saving but nothing happens. You have to upload the image again, then the text edit is saved. 

2. Please change the order of the images: the current on the top, the older ones below.

**Comment by Fiehra** [comment]
when adding new images to projects and images werent able to load the new image replaced the not loaded tree images
