### ISSUE TITLE
backoffice: add HTML-code option to editor

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#784]
Editing texts is much easier with HTML

**Comment by Fiehra** [comment]
add font package

yarn add @ckeditor/ckeditor5-font

**Comment by Fiehra** [comment]
yarn add  @ckeditor/ckeditor5-html-support

**Comment by Fiehra** [comment]
need to create custom ckeditor build from source with html support and then integrate to angular

https://ckeditor.com/docs/ckeditor5/latest/installation/integrations/angular.html
