### ISSUE TITLE
rankings: change buttons of last year / total

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#792]
Feedback from Micha; the selection should be dark, the other button green.
My suggestion: We should use a toogle/switch button without color change :)
examples: https://www.lambdatest.com/blog/top-20-css-toggle-switches-with-examples/

**Comment by Fiehra** [comment]
toggle buttons usually dont have much text for labels. how to make this with our labels.

changed colors for now
