### ISSUE TITLE
lower cases in english headlines 

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#803]
https://www.iplantatree.org/staging/plantSelf: 
title "Create your own planting" (the same in breadcrump please)

https://www.iplantatree.org/staging/plant: 
Tab "Plant yourself"
Link "Create planting now"
Link "Offer area now" (on all pages)

https://www.iplantatree.org/staging/plant
Button "Into plant bag" & after clicking "To plant bag"

https://www.iplantatree.org/staging/
Headline "Plant a tree"
Button "Plant tree now"
Process: "Plant bag" (instead of plantbag), "Plant a tree"

https://www.iplantatree.org/staging/editProfile/Christian:
"Edit profile"

**Comment by Fiehra** [comment]
also Plant bag for process header on homepage?

**Comment by Fiehra** [comment]
a
