### ISSUE TITLE
lower limit for PP-donations

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#810]
15 EUR

**Comment by Fiehra** [comment]
display paypal button for payments only when over 15eur

**Comment by Fiehra** [comment]
display infotext

**Comment by Fiehra** [comment]
adjust ngIf to include selectPlantbagPrice > 15

add selectPlantbagPrice observable

**Comment by Fiehra** [comment]
paypal Zahlungen erst ab 15 euro möglich


rename showPaypal to cookiesAccepted
