### ISSUE TITLE
links to user profiles do not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#828]

**Comment by gerolsteinernaturell** [comment]
How did you fix that? Apparently the URLs of the profiles have been changed (not just the link in the user backoffice). One user has already reported this. We have to fix this as soon as possible, as we are currently losing all backlinks.

**Comment by Fiehra** [comment]
replaced all navigation links to /user

**Comment by Fiehra** [comment]
also replaced search result in backend to use /user for the url
