### ISSUE TITLE
registration error (when a user name is already taken?)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#837]
I tried to register as "Test" and got this error message: "Ein unerwarteter Fehler ist aufgetreten."
Then I changed the name and that worked.
We should show an appropiate message: 
"Dieser Nutzername ist schon vergeben. Bitte wähle einen anderen."
"This username is already taken. Please choose another one."

**Comment by gerolsteinernaturell** [comment]
This problem still exists!?

**Comment by Fiehra** [comment]
caps not recognized in exception

**Comment by Fiehra** [comment]
other way around  convert database name to lowercase also
