### ISSUE TITLE
URL problem with special characters?

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#841]
User Bischof+Klein donated and I want to send them the URL for their profile, but it does not work (link from search and backoffice user):
https://www.iplantatree.org/user/Bischof%252BKlein%2520SE%2520%2526%2520Co.KG

**Comment by Fiehra** [comment]
bruh

**Comment by Fiehra** [comment]
https://stackoverflow.com/questions/4571346/how-to-encode-url-to-avoid-special-characters-in-java

**Comment by Fiehra** [comment]
hah einen fix gefunden   gabor checkts nochmal doppelt und deployed dann morgen
