### ISSUE TITLE
startpage (quick planting): display only available tree species

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#852]
currently I see 2 x Baumhasel and 1 x Wildkirsche, but we only have oaks. We should only show available tree species (so 3 x oak)

**Comment by Fiehra** [comment]
will only show 1 with oak instead of a triple oak

but checking for availability now

**Comment by gerolsteinernaturell** [comment]
1. Sometimes no tree is displayed at all. When I refresh, trees are displayed.
2. We should show 3 x the same tree species, if they are available in different projects.

**Comment by Fiehra** [comment]
might be problem of staging

on local its doing the desired behavior
