### ISSUE TITLE
user profile: faulty widget links

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#865]
The a href-links provided in the widget area have the wrong target (user profile). 
wrong:
<a href="https://iplantatree.org/p/u/user/stocubo"><img src="https://iplantatree.org/p/u/widget_2022?userName=stocubo&width=200&height=200&language=DEUTSCH" /></a>

correct:
<a href="https://iplantatree.org/user/stocubo"><img src="https://iplantatree.org/p/u/widget_2022?userName=stocubo&width=200&height=200&language=DEUTSCH" /></a>

**Comment by Fiehra** [comment]
host url gives backend url not frontend url
