### ISSUE TITLE
partner page: wrong position of the logos

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#867]
the logos should be before the corresponding paragraph (same topic as for the team page)

**Comment by Fiehra** [comment]
im guessing you mean about page not team page? @gerolsteinernaturell

**Comment by Fiehra** [comment]
changed order of image and paragraph and added caption html element

**Comment by gerolsteinernaturell** [comment]
@Fiehra I mean this page: https://www.iplantatree.org/partner
