### ISSUE TITLE
newsletter & blog overview page: Cookie button does not work

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#886]
Please add the same behavior like the paypal payment: When clicking on "Cookies erlauben" Button, the cookie popup pops up...

**Comment by gerolsteinernaturell** [comment]
this does not work properly on staging. One the newsetter page erverything is hidden until you accept the cookies and on the blog overview page only the button is visible. We should show the content, but the user has to accept the cookies to use the "Anmelden"-Button.

**Comment by Fiehra** [comment]
replace only the captcha instead of the whole newsletter when cookies are not accepted
