### ISSUE TITLE
improvement of startpage (see screenshot)

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#893]
To improve the user experience, we want to remove the static image on the homepage and add dynamic elements.
![Startseite IPAT](https://github.com/user-attachments/assets/33f8ae72-bd72-452b-9a8d-f11ce97bb99a)

1. remove the large static tree disc image so that you can see the line directly below it: Plant a tree (we should place the button a little lower).
2. underneath NEW: A tile with the **newest 4 plantings**, next to it the ranking with the **5 TOP donors of the last year** (both 50% width)
3. Add a "more"-link to the rankings page below or next to the 5 TOP donors
4. remove the line for area offer
5. below everything as before (process, projects...).

**Comment by Fiehra** [comment]
no anonymous plantings

**Comment by Fiehra** [comment]
try adding planted trees counter just under logo

**Comment by Fiehra** [comment]
add tooltip to the ranking button on rankings component
