### ISSUE TITLE
What do we need to use/integrate the/a HAL browser?

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/weplantaforest#9]

**Comment by mschaaf** [comment]
from the docu

> By default Spring Boot will serve static content from a folder called /static (or /public or /resources or /META-INF/resources) in the classpath

**Comment by jzillmann** [comment]
buah, docu reader....

**Comment by mschaaf** [comment]
main problem was that the jersey handler was setup for all url's under root (/).
