### ISSUE TITLE
blog pages: change link text

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#902]
The link text at the bottom of the blog pages is misleading. Please change from
"Zurück zum Blog" 
to
"Zurück zur Blog-Übersicht"

https://www.iplantatree.org/blog/1906

**Comment by gerolsteinernaturell** [comment]
link does not work on staging

**Comment by Fiehra** [comment]
rename to zurück zur übersicht

also adjust enlglish tranlation
