### ISSUE TITLE
user profiles: users should be able to delete their account 

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#905]
add a "Delete profile" button with a confirmation popup: 
"Do you really want to delete your profile? All personal data will be deleted. This cannot be undone." / "Willst du dein Profil wirklich löschen? Alle personenbezogenen Daten werden gelöscht. Dies lässt sich nicht rückgängig machen."

**Comment by Fiehra** [comment]
softdelete account

make users anonymous

**Comment by Fiehra** [comment]
replace Ok with Löschen , Delete,


check why it flickered 2nd time  why didn it close

**Comment by gerolsteinernaturell** [comment]
confirmation: replace Ok with Löschen

**Comment by gerolsteinernaturell** [comment]
confirmation: replace Ok with Löschen

**Comment by gerolsteinernaturell** [comment]
and we should use the alert popup for the confirmation, e.g. the one that pops up when you want to leave your team
