### ISSUE TITLE
staging: no HTML on projects pages

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#912]
the contents of the start page are now output as HTML (with long rows of numbers). This does not seem to work on the project pages.

**Comment by Fiehra** [comment]
can you pls add screenshot?

**Comment by gerolsteinernaturell** [comment]
Please see the HTML Code: view-source:https://staging.iplantatree.org/project/Hahnheide
the projects description is not there

**Comment by Fiehra** [comment]
check ssr

blog project pages

compare to faq

**Comment by Fiehra** [comment]
sometimes only the components appear not the html tags

**Comment by Fiehra** [comment]
google can fetch data when crawling. but more details about the crawling are not public. so only google knows about dynamic data fetching
all static content is prerendered on server though
