### ISSUE TITLE
user profile: icons "hanging in the air"

### ISSUE THREAD

**Issue by gerolsteinernaturell** [Dica-Developer/weplantaforest#921]
We should use buttons with the current icons for editing and deleting.

**Comment by Fiehra** [comment]
gave buttons their own row to make them fit on desktop  otherwise it looks weird and overflows

**Comment by Fiehra** [comment]
![image](https://github.com/user-attachments/assets/6dfa1444-7bb2-4175-a8bc-b3af3b2750bd)
